{% set name = "tweak" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9a349a68122fd86eaf0400616cb7bf026feab666190ad6824c492a9d012d9a62

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - tweak

about:
  home: https://github.com/kislyuk/tweak
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Application configuration engine

extra:
  recipe-maintainers:
    - pinin4fjords
