{% set name = "tweak" %}
{% set version = "1.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c444de0f0e48be80c052dfb5b0be0db70a5cedd6ef65f61a9bdee4b154302848

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - tweak

about:
  home: https://github.com/kislyuk/tweak
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE 
  summary: Application configuration engine

extra:
  recipe-maintainers:
    - pinin4fjords
